// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaMenu.Data;

#nullable disable

namespace PizzaMenu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240411105016_AddedPriceId")]
    partial class AddedPriceId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaMenu.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "House-Made Red Sauce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mozzarella Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ground Chuck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smoked Bacon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pickles"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cheddar Cheese"
                        });
                });

            modelBuilder.Entity("PizzaMenu.Models.ItemIngredient", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ItemIngredients");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 4
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 5
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 6
                        });
                });

            modelBuilder.Entity("PizzaMenu.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://d2s742iet3d3t1.cloudfront.net/restaurants/restaurant-79069000000000000/menu/items/3/item-500000023251982973_1675199226.png?size=medium",
                            Name = "American Cheeseburger Pizza",
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("PizzaMenu.Models.ItemIngredient", b =>
                {
                    b.HasOne("PizzaMenu.Models.Ingredient", "Ingredient")
                        .WithMany("ItemIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaMenu.Models.MenuItem", "Item")
                        .WithMany("ItemIngredients")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PizzaMenu.Models.Ingredient", b =>
                {
                    b.Navigation("ItemIngredients");
                });

            modelBuilder.Entity("PizzaMenu.Models.MenuItem", b =>
                {
                    b.Navigation("ItemIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
